# .github/workflows/firebase-hosting.yml
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out your repo
      - uses: actions/checkout@v4

      # Set up Node.js (use the same version as your project)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Build your app
      - name: Build project
        run: pnpm build

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CYBERLION_SITES_D0500 }}
          channelId: live
          projectId: cyberlion-sites-d0500
