# .github/workflows/firebase-hosting.yml
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Set up Node.js with caching for pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # 2. Set up pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 9   # or omit if your package.json has "packageManager"

      # 3. Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 4. Build your project
      - name: Build project
        run: pnpm build

      # 5. Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CYBERLION_SITES_D0500 }}
          channelId: live
          projectId: cyberlion-sites-d0500
